apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 647644443949.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newName: 647644443949.dkr.ecr.us-east-1.amazonaws.com/demo-frontend
  newTag: 9183c309
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
